// This file was autogenerated by ./node_modules/closure-library/closure/bin/build/depswriter.py.
// Please do not edit.
goog.addDependency('../../../../src/application.js', ['app.Application'], ['app.Collection', 'app.Config', 'app.View', 'app.Widget']);
goog.addDependency('../../../../src/builder.js', ['app.Builder'], []);
goog.addDependency('../../../../src/collection.js', ['app.Collection'], ['app.Config', 'app.Model']);
goog.addDependency('../../../../src/config.js', ['app.Config'], []);
goog.addDependency('../../../../src/model.js', ['app.Model'], ['app.Config']);
goog.addDependency('../../../../src/view.js', ['app.View'], ['app.Builder', 'app.Model']);
goog.addDependency('../../../../src/widget.js', ['app.Widget'], ['app.View']);
