// This file was autogenerated by ./node_modules/closure-library/closure/bin/build/depswriter.py.
// Please do not edit.
goog.addDependency('../../../../src/builder/builder.js', ['app.Builder'], []);
goog.addDependency('../../../../src/collection/collection.js', ['app.Collection'], ['app.Model']);
goog.addDependency('../../../../src/db/database.js', ['app.DataBase'], ['app.Collection']);
goog.addDependency('../../../../src/event/event.js', ['app.Event'], []);
goog.addDependency('../../../../src/model/model.js', ['app.Model'], []);
goog.addDependency('../../../../src/observer/observer.js', ['app.Observer'], []);
goog.addDependency('../../../../src/view/view.js', ['app.View'], ['app.Builder', 'app.Event', 'app.Model']);
goog.addDependency('../../../../src/view/widget.js', ['app.Widget'], ['app.View']);
